# Define the name for the stack
backend-api:
    image: 
    container_name: frontend-app  # Name of the container
    
    ports:
      - '5000:80'  # Map the container's port 3001 to the host machine's port 3001
 
